language: r
sudo: required
before_install:
  - sudo apt-get install libv8-dev
cache: packages
r_packages:
- remotes
- covr
matrix:
  include:
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_deploy:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: travis_wait 30 Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: 'true'
