language: r
sudo: required
cache: packages
# from https://github.com/stan-dev/rstanarm/blob/master/.travis.yml
before_install:
- mkdir -p ~/.R/
- echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
- echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars
apt_packages:
- libgdal-dev
- libgit2-dev
- libmagick++-dev
- libspatialite-dev
- libudunits2-dev
- libv8-dev
r_packages:
- remotes
- covr
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
env:
  global:
    - MAKEFLAGS="-j 2"
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
matrix:
  include:
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
#    before_deploy:
#    - Rscript -e 'remotes::install_cran("pkgdown")'
#    - Rscript -e 'remotes::install_github("kwb-r/pkgmeta")'
#    - Rscript -e 'remotes::install_github("kwb-r/kwb.pkgbuild")'
#    - Rscript -e 'pkgmeta::travis_pkg_install_script()'
#    - Rscript -e 'pkgmeta::write_pkg_codemeta_json(codemeta = pkgmeta::create_pkg_codemeta())'
#   deploy:
#      provider: script
#      script: Rscript -e 'kwb.pkgbuild::deploy_site_github_with_extra_files()'
#      skip_cleanup: 'true'
