language: r
sudo: required
before_install:
  - sudo apt-get install libv8-dev
  - sudo apt-get install libgit2-dev
  - sudo apt-get install libudunits2-dev
cache: packages
r_packages:
- remotes
- covr
matrix:
  include:
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_deploy:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    - Rscript -e 'remotes::install_github("kwb-r/pkgmeta")'
    - Rscript -e 'pkgmeta::travis_pkg_install_script()'
    - Rscript -e 'pkgmeta::write_pkg_codemeta_json(codemeta = pkgmeta::create_pkg_codemeta(pkgs = pkgmeta::get_github_packages(ignore_pkgs = "kwb.read")))'
    deploy:
      provider: script
      script: Rscript -e 'pkgmeta::deploy_site_github_with_extra_files()'
      skip_cleanup: 'true'
