---
title: "Analyse R Packages on Github"
author: "Michael Rustler"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Analyse R Packages}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# Install R Package Dependencies

## Get Public Github Package 
```{r, eval = FALSE}



secrets_csv <- "secrets.csv"

if(file.exists(secrets_csv))
secrets <- read.csv(secrets_csv, stringsAsFactors = FALSE)

Sys.setenv(GITHUB_PAT = secrets$github_token)
} else {
  ### GITHUB_PAT environment variable needs to be set in TRAVIS with access 
  ### rights limited to public repos (otherwise also private repos will be 
  ### analysed!)
}

options(github_token = Sys.getenv("GITHUB_PAT"))
pkgs <- pkgmeta::get_github_packages()
#saveRDS(pkgs,file = "rpackages.RData")

#pkgs <- readRDS("rpackages.RData")
#pkgs <- pkgmeta::get_github_packages()

#installed_packages <- rownames(installed.packages())
```` 

## Define paths 

```{r}
# Define paths and resolve placeholders

paths_list <- list(
  root_dir = tempdir(),
  pkglib = "<root_dir>/pkg-lib",
  pkgsource_dir = "<root_dir>/pkg-source",
  pkgnet_dir = "<root_dir>/pkgnet",
  pkgsource_zip_dir = "<pkgsource_dir>/zip",
  pkgsource_unzip_dir = "<pkgsource_dir>/unzip"
  )


paths <- kwb.utils::resolve(paths_list, root_dir = tempdir())
```




```{r}
fs::dir_create(paths$pkglib, recursive = TRUE)


withr::with_libpaths(new = paths$pkglib, {
  remotes::install_github("UptakeOpenSource/pkgnet@d1e974de299d46e71b082e027a71b8b254edc9b2",
  upgrade = "always")})
withr::with_libpaths(new = paths$pkglib, {
  remotes::install_github("ropensci/codemetar@dev")}
  )
withr::with_libpaths(new = paths$pkglib, {
  install.packages("purrr", repos = "https://cloud.r-project.org/")}
  )

```



## Install KWB packages (with dependencies in own library)

Required for "pkgnet" reports

```{r, eval = FALSE}
for(pkg in pkgs$name) {

withr::with_libpaths(new = paths$pkglib, {
  code = remotes::install_github(repo = sprintf("kwb-r/%s", pkg),
  dependencies = TRUE,
  upgrade = "always",
  auth_token =  Sys.getenv("GITHUB_PAT"))}
  )
}
```

## Download KWB packages as "source" 

Required for pkgnet "covr" and "codemetar"

```{r, eval = FALSE}

fs::dir_create(path = c(paths$pkgsource_zip_dir, paths$pkgsource_unzip_dir), 
               recursive = TRUE)

for(pkg in pkgs$name) {
  pkgmeta::download_github(repo = sprintf("kwb-r/%s", pkg),
                           dest_dir = paths$pkgsource_zip_dir,
                           use_zip = TRUE,
                           auth_token = Sys.getenv("GITHUB_PAT"))
}
zipfiles <- list.files(paths$pkgsource_zip_dir,full.names = TRUE)

invisible(lapply(zipfiles, function(x) {
  message(glue::glue("Unzipping {x} to {pkgsource_unzip_dir}"))
  unzip(x, exdir = paths$pkgsource_unzip_dir)}))

```

# Perform Package Meta Analysis

## With R package "pkgnet"

```{r, eval = FALSE}
fs::dir_create(paths$pkgnet_dir, recursive = TRUE)

withr::with_libpaths(new = path$pkglib,
                     code = for(x in pkgs$name) {
   print(sprintf("Write report for R package: %s", x))
   pkg_src_unzipped <- dir(paths$pkgsource_unzip_dir, pattern = x)
   if(length(pkg_src_unzipped) > 1) {
      stop(glue::glue("Multiple unzipped pkg sources found in {pkgsource_unzip_dir}:
                      {paste(pkg_src_unzipped, collapse = ', ')}.
                      Please delete the oldest one(s) manually"))
     #pkg_path <- file.path(pkgsource_unzip_dir, pkg_src_unzipped),
     #sapply(pkg_path, function(x) {max(fs::dir_info(pkg_path[x])$modification_time)})
    } else if(length(pkg_src_unzipped) == 0)  {
      stop(glue::glue("No unzipped pkg sources found in {pkgsource_unzip_dir}"))
    } else {
      try(pkgnet::CreatePackageReport(
         pkg_name = x,
         pkg_path = file.path(paths$pkgsource_unzip_dir, pkg_src_unzipped),
         report_path = file.path(paths$pkgnet_dir, paste0(x, ".html"))
        ))
  }})


```

## With R package "codemetar"

Generating "codemetar.json" file

```{r, eval = FALSE}
pkgs_codemetar <- withr::with_libpaths(new = paths$pkglib,
              code =lapply(pkgs$name,
                           function(x) {
                           print(glue::glue("Writing codemeta for R package {x}"))
                           codemetar::create_codemeta(pkg = x)}))
                                                     


jsonlite:::write_json(pkgs_codemetar,"codemetar.json",
                       useBytes = TRUE,
                       pretty = TRUE,
                       auto_unbox = TRUE)

```



